import PptxGenJS from 'pptxgenjs';
import { ICourse } from '../models/Course';

class ExportService {
  async generatePDF(course: ICourse): Promise<Buffer> {
    // Use puppeteer to generate PDF from HTML
    let browser;
    try {
      const puppeteer = require('puppeteer');
      browser = await puppeteer.launch({
        headless: true,
        executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined,
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
      });

      const page = await browser.newPage();

      const html = this.generateCourseHTML(course);
      await page.setContent(html, { waitUntil: 'networkidle0' });

      const pdfBuffer = await page.pdf({
        format: 'A4',
        margin: { top: '40px', bottom: '40px', left: '40px', right: '40px' },
        printBackground: true,
      });

      return Buffer.from(pdfBuffer);
    } finally {
      if (browser) {
        await browser.close();
      }
    }
  }

  private generateCourseHTML(course: ICourse): string {
    let html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: #4f46e5; border-bottom: 3px solid #4f46e5; padding-bottom: 12px; font-size: 28px; }
    h2 { color: #6366f1; margin-top: 32px; font-size: 22px; border-left: 4px solid #6366f1; padding-left: 12px; }
    h3 { color: #374151; font-size: 18px; margin-top: 20px; }
    p { margin: 8px 0; }
    img { max-width: 100%; height: auto; border-radius: 8px; margin: 12px 0; }
    .topic { page-break-before: always; }
    .topic:first-of-type { page-break-before: avoid; }
    .cover { text-align: center; padding: 60px 0; }
    .cover h1 { font-size: 36px; border: none; }
    .cover p { color: #6b7280; font-size: 16px; }
    .toc { margin: 24px 0; }
    .toc-item { padding: 4px 0; color: #4b5563; }
  </style>
</head>
<body>
  <div class="cover">
    <h1>${this.escapeHtml(course.title)}</h1>
    <p>Language: ${this.escapeHtml(course.language)}</p>
    <p>Generated by CourseBit</p>
  </div>
  <div class="toc">
    <h2>Table of Contents</h2>`;

    course.topics.forEach((topic, i) => {
      html += `<div class="toc-item">${i + 1}. ${this.escapeHtml(topic.title)}</div>`;
    });

    html += `</div>`;

    course.topics.forEach((topic, i) => {
      html += `<div class="topic">
        <h2>${i + 1}. ${this.escapeHtml(topic.title)}</h2>`;

      topic.subtopics.forEach((subtopic) => {
        html += `<h3>${this.escapeHtml(subtopic.title)}</h3>`;
        html += `<div>${subtopic.content}</div>`;
        if (subtopic.imageUrl) {
          html += `<img src="${subtopic.imageUrl}" alt="${this.escapeHtml(subtopic.title)}" />`;
        }
      });

      html += `</div>`;
    });

    html += `</body></html>`;
    return html;
  }

  async generatePPT(course: ICourse): Promise<Buffer> {
    const pptx = new PptxGenJS();
    pptx.layout = 'LAYOUT_16x9';
    pptx.author = 'CourseBit';
    pptx.title = course.title;

    // Title slide
    const titleSlide = pptx.addSlide();
    titleSlide.background = { fill: '4F46E5' };
    titleSlide.addText(course.title, {
      x: 0.5,
      y: 1.5,
      w: 9,
      h: 2,
      fontSize: 36,
      fontFace: 'Arial',
      color: 'FFFFFF',
      bold: true,
      align: 'center',
    });
    titleSlide.addText(`Language: ${course.language} | Generated by CourseBit`, {
      x: 0.5,
      y: 4,
      w: 9,
      h: 0.5,
      fontSize: 14,
      fontFace: 'Arial',
      color: 'C7D2FE',
      align: 'center',
    });

    // Table of contents
    const tocSlide = pptx.addSlide();
    tocSlide.addText('Table of Contents', {
      x: 0.5,
      y: 0.3,
      w: 9,
      h: 0.8,
      fontSize: 28,
      fontFace: 'Arial',
      color: '4F46E5',
      bold: true,
    });

    const tocText = course.topics
      .map((t, i) => `${i + 1}. ${t.title}`)
      .join('\n');
    tocSlide.addText(tocText, {
      x: 0.5,
      y: 1.3,
      w: 9,
      h: 4,
      fontSize: 16,
      fontFace: 'Arial',
      color: '374151',
      lineSpacingMultiple: 1.5,
    });

    // Content slides
    for (const topic of course.topics) {
      // Topic title slide
      const topicSlide = pptx.addSlide();
      topicSlide.background = { fill: 'EEF2FF' };
      topicSlide.addText(topic.title, {
        x: 0.5,
        y: 2,
        w: 9,
        h: 1.5,
        fontSize: 30,
        fontFace: 'Arial',
        color: '4F46E5',
        bold: true,
        align: 'center',
      });

      for (const subtopic of topic.subtopics) {
        const slide = pptx.addSlide();
        slide.addText(subtopic.title, {
          x: 0.5,
          y: 0.3,
          w: 9,
          h: 0.7,
          fontSize: 22,
          fontFace: 'Arial',
          color: '4F46E5',
          bold: true,
        });

        // Truncate content for slide readability
        const content = subtopic.content.substring(0, 800);
        const hasImage = !!subtopic.imageUrl;

        slide.addText(content, {
          x: 0.5,
          y: 1.1,
          w: hasImage ? 5.5 : 9,
          h: 4,
          fontSize: 12,
          fontFace: 'Arial',
          color: '374151',
          valign: 'top',
          wrap: true,
        });

        if (hasImage && subtopic.imageUrl) {
          try {
            slide.addImage({
              path: subtopic.imageUrl,
              x: 6.2,
              y: 1.1,
              w: 3.3,
              h: 2.5,
              rounding: true,
            });
          } catch {
            // Skip image if it fails to load
          }
        }
      }
    }

    const buffer = await pptx.write({ outputType: 'nodebuffer' });
    return buffer as Buffer;
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }
}

export const exportService = new ExportService();
