/**
 * Default text for the legal pages.
 *
 * /terms, /privacy, /refund and /cancellation existed as routes but there was
 * never any content behind them, so every one rendered "Page Not Found".
 * Stripe and PayPal both require these to be reachable before they will
 * approve a live account, so shipping without them is not an option.
 *
 * They are seeded only when missing — anything edited in the admin panel is
 * left alone.
 */

const BRAND = process.env.BRAND_NAME || 'Coursbit';
const SITE = (process.env.FRONTEND_URL || 'https://coursbit.com').replace(/\/$/, '');
const CONTACT = process.env.CONTACT_NOTIFY_EMAIL || process.env.SMTP_FROM_EMAIL || `support@${SITE.replace(/^https?:\/\//, '')}`;

export const DEFAULT_LEGAL_PAGES: { slug: string; content: string }[] = [
  {
    slug: 'terms',
    content: `# Terms of Service

_Last updated: ${new Date().toISOString().slice(0, 10)}_

## 1. Agreement

By creating an account or using ${BRAND} ("the Service") at ${SITE}, you agree to these Terms. If you do not agree, do not use the Service.

## 2. The Service

${BRAND} generates structured course material using third-party AI models. Generated content is produced automatically and is provided for learning and reference. You are responsible for reviewing it before relying on it, publishing it, or presenting it to others.

## 3. Accounts

You must provide accurate information when registering and keep your password secure. You are responsible for activity carried out under your account. You must be at least 16 years old, or the minimum age of digital consent in your country, whichever is higher.

## 4. Plans and billing

The Service offers a free plan and paid subscription plans. Paid plans renew automatically for the same period until cancelled. Prices are shown before purchase and include applicable taxes where required. Payments are processed by our payment providers; we do not store your card details.

## 5. Cancellation

You may cancel at any time from the billing page. Cancellation stops future renewals; access continues until the end of the period already paid for. See our Cancellation Policy and Refund Policy.

## 6. Acceptable use

You may not use the Service to generate or distribute unlawful, defamatory, harassing or infringing material, to attempt to gain unauthorised access to our systems, or to resell automated access to the AI generation features.

## 7. Your content

You retain ownership of the course titles and topics you submit. Subject to your compliance with these Terms, you may use the courses you generate for personal or commercial purposes. You grant us the limited right to store and process your content in order to operate the Service.

## 8. Availability

We aim for continuous availability but do not guarantee uninterrupted service. Features may change, and third-party AI providers may alter or withdraw their models.

## 9. Liability

To the maximum extent permitted by law, the Service is provided "as is". Our total liability for any claim is limited to the amount you paid us in the twelve months preceding the claim.

## 10. Termination

We may suspend or terminate accounts that breach these Terms. You may delete your account at any time from Settings.

## 11. Changes

We may update these Terms. Material changes will be announced on this page with a revised date.

## 12. Contact

Questions about these Terms: ${CONTACT}`,
  },
  {
    slug: 'privacy',
    content: `# Privacy Policy

_Last updated: ${new Date().toISOString().slice(0, 10)}_

## 1. Who we are

${BRAND}, operating ${SITE}, is the controller of the personal data described here. Contact: ${CONTACT}

## 2. What we collect

**Account data** — your name, email address and hashed password.
**Content data** — the course titles and topics you submit, and the courses, quizzes, notes and bookmarks generated from them.
**Billing data** — plan, subscription status and invoice records. Card details are handled by our payment providers and never reach our servers.
**Technical data** — IP address and basic request logs, kept for security and abuse prevention.

## 3. Why we use it

To provide and operate the Service, to process payments, to send transactional email (welcome, password reset, receipts, certificates), to prevent abuse, and to comply with legal obligations. We do not sell your data and we do not use it for advertising.

## 4. Legal basis

Performance of our contract with you (providing the Service), our legitimate interest (security and service improvement), and consent where required.

## 5. Processors

Course text is generated by third-party AI providers (such as OpenAI, Google and Anthropic), which receive the topic you submit in order to generate content. Payments are processed by Stripe, PayPal, Razorpay or Paystack depending on your region. Email is delivered by our SMTP provider. Hosting is provided by our infrastructure provider.

## 6. Retention

Account and course data is kept while your account exists. Deleting your account removes your courses, notes, bookmarks and certificates. Invoice records are retained where accounting law requires it.

## 7. Your rights

You may access, correct, export or delete your data, object to processing, or withdraw consent. Profile changes and account deletion are available in Settings; for anything else, write to ${CONTACT}. You may also complain to your local data protection authority.

## 8. Cookies

We use a strictly necessary cookie to keep you signed in. No advertising or third-party tracking cookies are set.

## 9. Security

Passwords are hashed with bcrypt. Traffic is encrypted in transit. Access to production data is restricted.

## 10. Children

The Service is not directed at children under 16.

## 11. Changes

Material changes to this policy will be published here with a revised date.`,
  },
  {
    slug: 'refund',
    content: `# Refund Policy

_Last updated: ${new Date().toISOString().slice(0, 10)}_

## Fourteen-day refund

If you are not satisfied with a paid plan, contact us within **14 days** of the charge at ${CONTACT} and we will refund it in full. No explanation is required.

## Renewals

Automatic renewals are refundable within **7 days** of the renewal charge, provided the plan has not been used to generate courses in that period.

## How to request

Email ${CONTACT} from the address on your account, stating the charge date. We respond within 2 business days and process approved refunds within 5–10 business days, back to the original payment method.

## Exceptions

We may decline refunds where the account has breached our Terms of Service, or where a pattern of repeated refund requests indicates abuse.

## Statutory rights

Nothing here limits any refund or withdrawal right you have under the consumer law of your country.`,
  },
  {
    slug: 'cancellation',
    content: `# Cancellation Policy

_Last updated: ${new Date().toISOString().slice(0, 10)}_

## Cancelling

You can cancel your subscription at any time from the **Billing** page. Cancellation takes effect immediately in the sense that no further payments are taken.

## What happens to your access

You keep full access to paid features until the end of the period you have already paid for. After that the account returns to the free plan.

## What happens to your courses

Nothing is deleted. Your courses, notes, bookmarks and certificates remain in your account on the free plan, subject to the free plan's limits on creating new courses.

## Resubscribing

You can resubscribe at any time from the Billing page; a new billing period starts from that date.

## Deleting your account

Deleting your account in Settings is permanent and removes your data. Cancel your subscription first if one is active.

## Questions

${CONTACT}`,
  },
];
